#!/bin/bash
################################################################################
# display.sh — Banner, main menu displays, and print helpers
# Extracted from rhoai-toolkit.sh
################################################################################

_DISPLAY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

print_banner() {
    echo ""
    echo -e "${MAGENTA}╔════════════════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${MAGENTA}║                                                                            ║${NC}"
    echo -e "${MAGENTA}║          🚀 Complete OpenShift + RHOAI + MaaS Setup 🚀                    ║${NC}"
    echo -e "${MAGENTA}║                                                                            ║${NC}"
    echo -e "${MAGENTA}╚════════════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

show_main_menu() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                    Main Menu                                   ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${MAGENTA}Quick Start:${NC}"
    echo -e "${YELLOW}1)${NC} Install RHOAI 3.5 ${GREEN}[Recommended]${NC}"
    echo -e "${YELLOW}2)${NC} Workshop Demo Setup (RHOAI 3.5 + OpenWebUI) ${GREEN}[Workshops]${NC}"
    echo ""
    echo -e "${MAGENTA}Advanced Installation:${NC}"
    echo -e "${YELLOW}3)${NC} Complete Setup (OpenShift + RHOAI 3.x + GPU + MaaS) ${MAGENTA}[Full]${NC}"
    echo -e "${YELLOW}4)${NC} Minimal RHOAI 3.x Setup (choose operators) ${CYAN}[Flexible]${NC}"
    echo ""
    echo -e "${MAGENTA}Management & Tools:${NC}"
    echo -e "${YELLOW}5)${NC} RHOAI Management (configure features, deploy models, etc.)"
    echo -e "${YELLOW}6)${NC} Create GPU MachineSet (add GPU nodes to existing cluster)"
    echo -e "${YELLOW}7)${NC} GPU & ClusterPolicy Management ${CYAN}[NVIDIA]${NC}"
    echo -e "${YELLOW}8)${NC} Configure Kubeconfig (login, set, or create kubeconfig) ${CYAN}[Connection]${NC}"
    echo -e "${YELLOW}a)${NC} TLS Certificate Setup (Let's Encrypt / Self-signed)"
    echo -e "${YELLOW}h)${NC} Help (show scripts and documentation)"
    echo -e "${YELLOW}0)${NC} Exit"
    echo ""
    echo -e "${CYAN}Tip:${NC} Use command mode to skip menus: ${GREEN}./rhoai-toolkit.sh deploy demo webui${NC}"
    echo -e "     Type ${GREEN}./rhoai-toolkit.sh help${NC} for all available commands."
    echo ""
}

show_rhoai_management_menu() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                 RHOAI Management Menu                          ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${YELLOW}1)${NC} Model Management ${BLUE}→${NC}"
    echo "    Deploy models, test in Playground, create GPU profiles"
    echo ""
    echo -e "${YELLOW}2)${NC} AI Services & Infrastructure ${BLUE}→${NC}"
    echo "    Setup MaaS, LlamaStack, MCP Servers, Feature Store"
    echo ""
    echo -e "${YELLOW}3)${NC} Demos ${GREEN}[Version-Aware]${NC} ${BLUE}→${NC}"
    echo "    Deploy ready-to-use demos (Banking, LlamaStack, GuideLLM)"
    echo ""
    echo -e "${YELLOW}4)${NC} RHOAI 3.2+ Features ${GREEN}[NEW]${NC} ${BLUE}→${NC}"
    echo "    llm-d, MLflow, Observability (per CAI Guide)"
    echo ""
    echo -e "${YELLOW}5)${NC} Dashboard & Configuration"
    echo "    Enable features like Model Registry, GenAI Studio"
    echo ""
    echo -e "${YELLOW}6)${NC} Quick Start Wizard ${MAGENTA}✨${NC}"
    echo "    Run typical post-install workflow"
    echo ""
    echo -e "${YELLOW}7)${NC} Day 2 Operations ${BLUE}→${NC}"
    echo "    Approve CSRs, remove kubeadmin, cluster maintenance"
    echo ""
    echo -e "${YELLOW}8)${NC} Troubleshooting & Fixes ${RED}[Fixes]${NC}"
    echo "    GPU operator issues, CUDA compatibility, common problems"
    echo ""
    echo -e "${YELLOW}0)${NC} Back to Main Menu"
    echo ""
}

show_feast_submenu() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                 Feature Store (Feast)                          ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${MAGENTA}What is Feast?${NC}"
    echo "    A feature store bridges ML training and serving, ensuring"
    echo "    consistent features and eliminating training-serving skew."
    echo ""
    echo -e "${YELLOW}1)${NC} Enable Feast Operator"
    echo "    Enable feastoperator in DataScienceCluster (required first)"
    echo ""
    echo -e "${YELLOW}2)${NC} Setup Custom Feature Store"
    echo "    Create a FeatureStore with custom Git repository"
    echo ""
    echo -e "${YELLOW}3)${NC} Show Feature Store Status"
    echo "    View all FeatureStores and their status"
    echo ""
    echo -e "${YELLOW}4)${NC} Diagnose Feature Store ${GREEN}[Version-Aware]${NC}"
    echo "    Troubleshoot visibility issues (3.2 → 3.3 upgrades)"
    echo ""
    echo -e "${YELLOW}5)${NC} Delete Feature Store"
    echo "    Remove a FeatureStore from a namespace"
    echo ""
    echo -e "${YELLOW}6)${NC} Run feast apply (register features)"
    echo "    Execute feast apply in an existing FeatureStore pod"
    echo ""
    echo -e "${YELLOW}7)${NC} Run feast materialize (populate online store)"
    echo "    Execute feast materialize for real-time serving"
    echo ""
    echo -e "${CYAN}Tip: Deploy demos from: RHOAI Management → Demos${NC}"
    echo ""
    echo -e "${YELLOW}0)${NC} Back to AI Services"
    echo ""
}

show_model_management_submenu() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                 Model Management                               ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${MAGENTA}Model Deployment:${NC}"
    echo -e "${YELLOW}1)${NC} Deploy GenAI Model"
    echo "    Interactive LLM deployment (vLLM, llm-d, etc.)"
    echo ""
    echo -e "${YELLOW}2)${NC} Deploy Predictive Model ${GREEN}[New]${NC}"
    echo "    Deploy sklearn/xgboost/lightgbm/onnx from S3/MinIO (CPU)"
    echo ""
    echo -e "${YELLOW}3)${NC} Add Model to Playground"
    echo "    Test models interactively in GenAI Studio"
    echo ""
    echo -e "${MAGENTA}Model Storage (HuggingFace → S3):${NC}"
    echo -e "${YELLOW}4)${NC} Setup Model Storage (MinIO) ${GREEN}[New]${NC}"
    echo "    Deploy MinIO S3 storage for HuggingFace models"
    echo ""
    echo -e "${YELLOW}5)${NC} Download Model from HuggingFace ${GREEN}[New]${NC}"
    echo "    Download models to S3 for deployment"
    echo ""
    echo -e "${MAGENTA}Serving Runtimes:${NC}"
    echo -e "${YELLOW}6)${NC} Manage Serving Runtimes ${GREEN}[New]${NC}"
    echo "    Add/export runtimes (vLLM-Omni, Community vLLM, Red Hat vLLM)"
    echo ""
    echo -e "${MAGENTA}Hardware Profiles:${NC}"
    echo -e "${YELLOW}7)${NC} Create GPU Hardware Profile (Custom)"
    echo "    Define custom GPU resources for model deployments"
    echo ""
    echo -e "${YELLOW}8)${NC} Quick GPU Profile Setup ${GREEN}[Recommended]${NC}"
    echo "    Create pre-configured profiles (Small/Medium/Large)"
    echo ""
    echo -e "${MAGENTA}Model Catalog:${NC}"
    echo -e "${YELLOW}9)${NC} Manage Model Catalog ${GREEN}[Add/Remove/List]${NC}"
    echo "    Add, remove, rename entries in the RHOAI Model Catalog"
    echo ""
    echo -e "${YELLOW}0)${NC} Back to RHOAI Management"
    echo ""
}

show_ai_services_submenu() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║             AI Services & Infrastructure                       ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${MAGENTA}Model as a Service (MaaS):${NC}"
    echo -e "${YELLOW}1)${NC} Setup MaaS ${GREEN}[Version-Aware]${NC}"
    echo "    API gateway for model serving (auto-configures for RHOAI version)"
    echo ""
    echo -e "${MAGENTA}LlamaStack:${NC}"
    echo -e "${YELLOW}2)${NC} Setup LlamaStack (Generic)"
    echo "    Deploy LlamaStack with vLLM, Azure, OpenAI, Ollama, or Bedrock"
    echo ""
    echo -e "${YELLOW}3)${NC} Enable LlamaStack Operator"
    echo "    Enable LlamaStack operator in DataScienceCluster"
    echo ""
    echo -e "${MAGENTA}Feature Store (Feast):${NC}"
    echo -e "${YELLOW}4)${NC} Feature Store Management ${BLUE}→${NC}"
    echo "    Setup and manage Feature Store for ML features"
    echo ""
    echo -e "${MAGENTA}Model Registry:${NC}"
    echo -e "${YELLOW}5)${NC} Setup Model Registry ${GREEN}[NEW]${NC}"
    echo "    Deploy MySQL + create ModelRegistry instance"
    echo ""
    echo -e "${MAGENTA}AI Pipelines:${NC}"
    echo -e "${YELLOW}6)${NC} Setup Pipeline Server ${GREEN}[NEW]${NC}"
    echo "    Deploy DSPA with S3 storage (reuse existing MinIO or new)"
    echo ""
    echo -e "${MAGENTA}MCP Servers (Tool Calling):${NC}"
    echo -e "${YELLOW}7)${NC} MCP Server Management ${BLUE}→${NC}"
    echo "    Weather MCP, Kubernetes MCP, and other tool servers"
    echo ""
    echo -e "${CYAN}Tip: Deploy demos from: RHOAI Management → Demos${NC}"
    echo ""
    echo -e "${YELLOW}0)${NC} Back to RHOAI Management"
    echo ""
}

show_demos_submenu() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                    Demos ${GREEN}[Version-Aware]${NC}                       ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${MAGENTA}Feature Store:${NC}"
    echo -e "${YELLOW}1)${NC} Deploy Banking Demo (Feast)"
    echo "    Banking feature store with customer/transaction features"
    echo ""
    echo -e "${MAGENTA}Chat & AI Assistants:${NC}"
    echo -e "${YELLOW}2)${NC} Deploy Open WebUI ${GREEN}[Recommended]${NC}"
    echo "    Web interface for chatting with models (OpenAI-compatible)"
    echo ""
    echo -e "${YELLOW}3)${NC} Deploy LlamaStack Demo"
    echo "    Full demo with Weather MCP Server, MongoDB, and Streamlit UI"
    echo ""
    echo -e "${MAGENTA}Benchmarking & Testing:${NC}"
    echo -e "${YELLOW}4)${NC} Deploy GuideLLM"
    echo "    LLM benchmarking tool (TTFT, ITL, throughput, latency)"
    echo ""
    echo -e "${MAGENTA}AI Safety:${NC}"
    echo -e "${YELLOW}5)${NC} Deploy Guardrails Demo ${GREEN}[TrustyAI]${NC}"
    echo "    PII detection, content filtering with Guardrails Orchestrator"
    echo ""
    echo -e "${MAGENTA}API Gateway:${NC}"
    echo -e "${YELLOW}6)${NC} MaaS Demo ${GREEN}[Interactive]${NC}"
    echo "    Chat with models, compare responses, view metrics"
    echo ""
    echo -e "${MAGENTA}Additional Demos:${NC}"
    echo -e "${YELLOW}7)${NC} Financial Loan Demo ${GREEN}[Predictive + GenAI]${NC}"
    echo "    ML model training + LLM fine-tuning + web app"
    echo ""
    echo -e "${YELLOW}8)${NC} Marketing Assistant Demo ${YELLOW}[3x L40S GPU]${NC}"
    echo "    Multi-agent A2A campaign manager with TrustyAI guardrails"
    echo ""
    echo -e "${YELLOW}9)${NC} AI Pipeline Demo ${GREEN}[KFP + Elyra]${NC}"
    echo "    End-to-end ML pipeline with Model Registry versioning"
    echo ""
    echo -e "${YELLOW}10)${NC} NeMo Guardrails Demo ${GREEN}[RHOAI 3.4]${NC}"
    echo "    CRD-based guardrails with PII detection and self-check rails"
    echo ""
    echo -e "${YELLOW}11)${NC} LMEval Builder Lab ${GREEN}[Benchmarks]${NC}"
    echo "    Korean language benchmarks + GuideLLM + MLflow tracking"
    echo ""
    echo -e "${YELLOW}12)${NC} n8n Workflow Automation"
    echo "    Deploy n8n workflow automation tool"
    echo ""
    echo -e "${YELLOW}13)${NC} MaaS Rate Limiting Demo ${GREEN}[API Keys + 429]${NC}"
    echo "    Workbench with notebook to test API key auth and token rate limits"
    echo ""
    echo -e "${MAGENTA}Technology Preview:${NC}"
    echo -e "${YELLOW}14)${NC} AutoML Demo ${YELLOW}[Tech Preview]${NC}"
    echo "    Automated ML model training via AutoGluon + Kubeflow Pipelines"
    echo ""
    echo -e "${YELLOW}15)${NC} AutoRAG Demo ${YELLOW}[Tech Preview]${NC}"
    echo "    Automated RAG pipeline optimization (requires Llama Stack + Milvus)"
    echo ""
    echo -e "${MAGENTA}Tracing & Ops:${NC}"
    echo -e "${YELLOW}17)${NC} MLflow Tracing Demo ${GREEN}[Banking Multi-Agent]${NC}"
    echo -e "${YELLOW}18)${NC} Lightspeed + MCP Troubleshooting Demo"
    echo ""
    echo -e "${MAGENTA}Environment:${NC}"
    echo -e "${YELLOW}19)${NC} Deploy Full Demo Environment ${GREEN}[All-in-One]${NC}"
    echo "    Deploy all demos (except Marketing Assistant)"
    echo ""
    echo -e "${YELLOW}0)${NC} Back to RHOAI Management"
    echo ""
}

show_rhoai32_features_submenu() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║           RHOAI 3.2+ Features (per CAI Guide)                  ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${MAGENTA}Model Serving (llm-d):${NC}"
    echo -e "${YELLOW}1)${NC} Setup llm-d Infrastructure ${GREEN}[Required]${NC}"
    echo "    GatewayClass, Gateway, RHCL/Kuadrant for authentication"
    echo ""
    echo -e "${YELLOW}2)${NC} Deploy LLMInferenceService"
    echo "    Deploy a model using llm-d runtime (RHOAI 3.2+, requires OCP 4.20+)"
    echo ""
    echo -e "${MAGENTA}New Operators:${NC}"
    echo -e "${YELLOW}3)${NC} Enable MLflow Operator ${GREEN}[NEW]${NC}"
    echo "    Experiment tracking, model versioning, artifact storage"
    echo ""
    echo -e "${YELLOW}4)${NC} Enable LlamaStack Operator"
    echo "    LlamaStack distribution management"
    echo ""
    echo -e "${MAGENTA}Observability:${NC}"
    echo -e "${YELLOW}5)${NC} Enable Cluster Monitoring for KServe"
    echo "    UserWorkloadMonitoring for KServe metrics"
    echo ""
    echo -e "${YELLOW}6)${NC} Configure DSCInitialization Observability"
    echo "    Metrics storage, distributed tracing with Tempo"
    echo ""
    echo -e "${MAGENTA}Configuration:${NC}"
    echo -e "${YELLOW}7)${NC} Setup MCP Servers ConfigMap (3.2 format)"
    echo "    New JSON format for MCP server configuration"
    echo ""
    echo -e "${YELLOW}0)${NC} Back to RHOAI Management"
    echo ""
}

print_header() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║ $1${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_step() {
    echo -e "${YELLOW}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${CYAN}ℹ $1${NC}"
}
